spring:
  application:
    name: Schedule
  mvc:
    view:
      prefix: /view/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SCH
    username: root
    password: 
server:
  port: 8080
#  servlet:
#    context-path: /test
